### PR TITLE
fix GCC11 compilation

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by cotequeiroz** [comment]
I don't really know if it matters, but this won't produce the same result as before.  The assignment with uint32_t will set 4 bytes of the 6 needed, the other two will be uninitialized.  What you could write to produce the exact same result as before is something like:
``` C
    uint64_t mac_src = m;
    memcpy(&this_mac.u8, &mac_src, ETH_ALEN < sizeof (uint64_t) ? ETH_ALEN : sizeof (uint64_t));
```

**Comment by neheb** [comment]
that's just bizarre.

**Comment by namidairo** [comment]
>     memcpy(&this_mac.u8, &mac_src, ETH_ALEN < sizeof (uint64_t) ? ETH_ALEN : sizeof (uint64_t));

Isn't the ternary here a big no-op since it would evaluate the same way on basically everything? (Unless you have a target that somehow manages to fit uint64_t into less than 6 bytes...)

**Comment by cotequeiroz** [comment]
I’d say my coding style is an acquired taste. 🤣 

The compiler should take care of the no-op.

**Comment by neheb** [comment]
Updated commit with the given solution.

**Comment by PolynomialDivision** [comment]
thanks, I was also unsure. I just merged. It will not influence dawn since only for testing.

**Pull request merged**
