### PR TITLE
network: dump detail on ping pong received

### PR DESCRIPTION
**Pull request by ptpt52**
This also fix a typo error on check_timeout on wrong list

Fixes: https://github.com/berlin-open-wireless-lab/DAWN/commit/47e98efed6ccb878227bc1c94e4e74b4ca97d8d5 ("network: ping pong keepalive for tcp connections")

@PolynomialDivision  
this really my typo

### CODE REVIEW

**Comment by ptpt52** [comment]
@PolynomialDivision 
hi, what do you think about usteer(https://openwrt.org/usteer)

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision hi, what do you think about usteer(https://openwrt.org/usteer)

Did not test it myself. I always have a look what they do as hostapd extension, and what new features they have. For example, they now calcualte the RSSI from RCPI or RSNI, however when I tried something like that, it had unknow offsets. :/
What do you think of it or why do you use dawn?

**Comment by ptpt52** [comment]
@PolynomialDivision 
It seems that usteer is much cleaner and simpler to implement, it only uses udp broadcast communication, although there will be broadcast pollution of the network. It is also because of the broadcast communication that usteer does not need the umdns component like dawn, and there are still some bugs in the umdns formation so far.
I'm not sure how well the test works yet, I may try usteer again in the next product release

**Comment by PolynomialDivision** [comment]
I also used multicast and broadcast. I have that as options in my code. However, I needed in the early days of dawn a reliable synchronization between all my APs.

Not sure if it is a good idea to have two projects that are doing almost the same thing. At least the 802.11v/k support is getting better and better over time. :)

**Pull request merged**
