### PR TITLE
tcpsocket: fix read callback function

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by XiaoliChan** [comment]
Great, I have test this PR

I meet a serious issue that is AP can not connect each other

Here is my one of AP log:
```
Fri Aug  7 01:24:37 2020 daemon.info dawn[2972]: --------Connections------
Fri Aug  7 01:24:37 2020 daemon.info dawn[2972]: Connecting to Port: 1026, Connected: True
Fri Aug  7 01:24:37 2020 daemon.info dawn[2972]: ------------------
Fri Aug  7 01:24:37 2020 daemon.info dawn[2972]: Ustream send: 196
Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: reading body...
Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: processing message...
Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: reading body...
Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: processing message...
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: [Thread] : Removing old probe entries!
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: [Thread] : Removing old entries finished!
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: [ULOOP] : Processing denied authentication!
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: [Thread] : Removing old client entries!
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Sending beacon report!
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Sending beacon report Sub!
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Sending beacon report Sub!
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: tcp_socket: reading body...
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: tcp_socket: processing message...
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: --------Connections------
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Connecting to Port: 1026, Connected: True
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: ------------------
Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Ustream send: 1508
```

```
Fri Aug  7 01:25:44 2020 daemon.info dawn[2972]: --------Connections------
Fri Aug  7 01:25:44 2020 daemon.info dawn[2972]: Connecting to Port: 1026, Connected: True
Fri Aug  7 01:25:44 2020 daemon.info dawn[2972]: ------------------
Fri Aug  7 01:25:44 2020 daemon.info dawn[2972]: Ustream send: 196
Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: reading body...
Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: processing message...
Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: reading body...
Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: processing message...
Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: reading body...
Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: processing message...
Fri Aug  7 01:25:46 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
Fri Aug  7 01:25:46 2020 daemon.info dawn[2972]: tcp_socket: reading body...
Fri Aug  7 01:25:46 2020 daemon.info dawn[2972]: tcp_socket: processing message...
```

**Comment by PolynomialDivision** [comment]
> Great, I have test this PR
> 
> I meet a serious issue that is AP can not connect each other in this PR
> 
> Here is my one of AP log:
> 
> ```
> Fri Aug  7 01:24:37 2020 daemon.info dawn[2972]: --------Connections------
> Fri Aug  7 01:24:37 2020 daemon.info dawn[2972]: Connecting to Port: 1026, Connected: True
> Fri Aug  7 01:24:37 2020 daemon.info dawn[2972]: ------------------
> Fri Aug  7 01:24:37 2020 daemon.info dawn[2972]: Ustream send: 196
> Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
> Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: reading body...
> Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: processing message...
> Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
> Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: reading body...
> Fri Aug  7 01:24:38 2020 daemon.info dawn[2972]: tcp_socket: processing message...
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: [Thread] : Removing old probe entries!
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: [Thread] : Removing old entries finished!
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: [ULOOP] : Processing denied authentication!
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: [Thread] : Removing old client entries!
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Sending beacon report!
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Sending beacon report Sub!
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Sending beacon report Sub!
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: tcp_socket: reading body...
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: tcp_socket: processing message...
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: --------Connections------
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Connecting to Port: 1026, Connected: True
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: ------------------
> Fri Aug  7 01:24:39 2020 daemon.info dawn[2972]: Ustream send: 1508
> ```
> 
> ```
> Fri Aug  7 01:25:44 2020 daemon.info dawn[2972]: --------Connections------
> Fri Aug  7 01:25:44 2020 daemon.info dawn[2972]: Connecting to Port: 1026, Connected: True
> Fri Aug  7 01:25:44 2020 daemon.info dawn[2972]: ------------------
> Fri Aug  7 01:25:44 2020 daemon.info dawn[2972]: Ustream send: 196
> Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
> Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: reading body...
> Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: processing message...
> Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
> Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: reading body...
> Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: processing message...
> Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
> Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: reading body...
> Fri Aug  7 01:25:45 2020 daemon.info dawn[2972]: tcp_socket: processing message...
> Fri Aug  7 01:25:46 2020 daemon.info dawn[2972]: tcp_socket: commencing message...
> Fri Aug  7 01:25:46 2020 daemon.info dawn[2972]: tcp_socket: reading body...
> Fri Aug  7 01:25:46 2020 daemon.info dawn[2972]: tcp_socket: processing message...
> ```

Sry, u are to quick. That was just something for me and @Ian-Clowes
I wanted to link to some code @Ian-Clowes wrote and have it nice formated. ;)

I'm already trying to fix it. Actually connection to the other AP works, but the read callback is not working correctly. I'm working on a fix.

**Comment by PolynomialDivision** [comment]
@XiaoliChan Should work now. ;) And hopefully it will fix memory issues.

**Comment by PolynomialDivision** [comment]
@Ian-Clowes since you're so into performance, which I find pretty cool, do we want to keep the header or reduce the alloc to -4 and overrite the information, since it is already in final_len?

**Comment by Ian-Clowes** [comment]
4 bytes won't make a difference :).  I like performance, but also like code to be "obvious" so that I can understand it next time I look.  So let.s keep the buffer being everything coming off of the wire so that it is indeed the message.

**Comment by Ian-Clowes** [comment]
buffer = length bytes + data

**Comment by PolynomialDivision** [comment]
Okay. I will write a better commit message and pull that to master. Further, I will update the openwrt package repro. Let's see if that will fix the memory issue.

**Comment by Ian-Clowes** [comment]
There is still a memory leak somewhere.  ~100kb/hour on my little system I think.  Hard to tell when I stop and start things so much.  I'm going to run AP on its own tomorrow to see if that slows it down.  If so I'll infer it is something to do with TCP handling.  Then I'll run with wi-fi disabled and see what that does.  Also want to look at all the pointer types in the code to add more dawn_memreg() ij caase that spots things.  May turn back to getting a glibc variant up and running if ASAN is the only thing that can find the leak in a library somewhere.

**Comment by XiaoliChan** [comment]
Yep, connection working, thank you @PolynomialDivision @Ian-Clowes 

But i found `HearingMap` working strange
<a></a>

The `HearingMap` did not show my client correctly because not only one client connecting in my 5GHz wifi. By the way, it did not show a compare thing like 2.4GHz which I have mark

The second issue is the `Chosen AP` function work bad (the client `02:9E:2F:C3:BD:C5` is close to another ap not current ap)
```
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: -------- KICKING CLIENTS!!!---------
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: EVAL 20:76:93:3E:3A:F2
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: Calculating own score!
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: Score: 100 of:
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: bssid_addr: 20:76:93:3E:3A:F2, client_addr: 02:9E:2F:C3:BD:C5, signal: -66, freq: 5260, counter: 5, vht: 1, min_rate: 49, max_rate: 56
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: Own Score! Skipping!
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: bssid_addr: 20:76:93:3E:3A:F2, client_addr: 02:9E:2F:C3:BD:C5, signal: -66, freq: 5260, counter: 5, vht: 1, min_rate: 49, max_rate: 56
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: Chosen AP
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: AP is best. Client will stay:
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: bssid_addr: 20:76:93:3E:3A:F2, client_addr: 02:9E:2F:C3:BD:C5, freq: 5260, ht_supported: 1, vht_supported: 1, ht: 1, vht: 1, kick: 0
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: Calculating own score!
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: Score: 200 of:
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: bssid_addr: 20:76:93:3E:3A:F2, client_addr: 6C:6A:77:5F:5F:73, signal: -54, freq: 5260, counter: 7, vht: 1, min_rate: 0, max_rate: 0
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: Own Score! Skipping!
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: bssid_addr: 20:76:93:3E:3A:F2, client_addr: 6C:6A:77:5F:5F:73, signal: -54, freq: 5260, counter: 7, vht: 1, min_rate: 0, max_rate: 0
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: Chosen AP
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: AP is best. Client will stay:
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: bssid_addr: 20:76:93:3E:3A:F2, client_addr: 6C:6A:77:5F:5F:73, freq: 5260, ht_supported: 1, vht_supported: 1, ht: 1, vht: 1, kick: 0
Fri Aug  7 12:18:21 2020 daemon.info dawn[2000]: ---------------------------
```

**Comment by Ian-Clowes** [comment]
Can you show the hearing map for 02:9E:2F:C3:BD:C5?  The scores on there should be what the kicking algorithm used and allow an explanation of what you're seeing.

**Comment by Ian-Clowes** [comment]
@XiaoliChan , and thanks for trying things out and reporting back.  It looks like you have a great network to explore whether all the algorithms are working correctly, so I hope you'll stay with us to make them as good as they can be.  I only have a simple home network so can see the basics working, but don't have a multitude of devices coming and going.

**Comment by XiaoliChan** [comment]
> @XiaoliChan , and thanks for trying things out and reporting back. It looks like you have a great network to explore whether all the algorithms are working correctly, so I hope you'll stay with us to make them as good as they can be. I probably spend too much time looking at the code to fix little bugs and quirks that I see and not at what it is achieving when running!

No at all, I am very glad to test with you.

**Comment by XiaoliChan** [comment]
**Here is the first situation: 02:9E:2F:C3:BD:C5 is close to the ap of room1**

_Catch on room1 ap_
```
        "Hydrogen-5G": {
                "02:9E:2F:C3:BD:C5": {
                        "20:76:93:3E:3A:F2": {
                                "signal": -53,
                                "rcpi": -1,
                                "rsni": -1,
                                "freq": 5260,
                                "ht_capabilities": true,
                                "vht_capabilities": true,
                                "channel_utilization": 1,
                                "num_sta": 2,
                                "ht_support": true,
                                "vht_support": true,
                                "score": 200
                        }
                }
        }
}
root@AP-Room1:~# 

```

**Next, this is the second situation: 02:9E:2F:C3:BD:C5 is close to the ap of living room**

_Catch on room1 ap_
```
        "Hydrogen-5G": {
                "02:9E:2F:C3:BD:C5": {
                        "20:76:93:3E:3A:F2": {
                                "signal": -73,
                                "rcpi": -1,
                                "rsni": -1,
                                "freq": 5260,
                                "ht_capabilities": true,
                                "vht_capabilities": true,
                                "channel_utilization": 1,
                                "num_sta": 2,
                                "ht_support": true,
                                "vht_support": true,
                                "score": 100
                        }
                }
        }
}
root@AP-Room1:~# 

```

**Pull request merged**
