### PR TITLE
tcpsocket: free con after ustream write error

### PR DESCRIPTION
**Pull request by babarosaM33**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
This patch does not apply after applying https://github.com/berlin-open-wireless-lab/DAWN/pull/101

**Comment by babarosaM33** [comment]
maybe, you could test #101 first.

this patch is on the master branch.

**Comment by PolynomialDivision** [comment]
@babarosaM33 could u update the PR by pulling the latest master changes into your branch? I can not apply this patch on my current master. I could rebase, but I'm afraid that I will destroy something.

**Comment by babarosaM33** [comment]
new pr #105

**Pull request closed without merging**
