### PR TITLE
Use fixed size and endianness for length prefix of network messages

### PR DESCRIPTION
**Pull request by dwmw2**
We can't use host-dependent endianness for network traffic.
The size of size_t also varies from host to host so stick with uint32_t.

Fixes: #92

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Thanks a lot! Could you please change the commit header to something like

     tcpsocket: use fixed size and endianness for length prefix of network messages

**Comment by dwmw2** [comment]
Done; thanks.

**Comment by PolynomialDivision** [comment]
Thank u I will merge then build bot process is finished!

**Comment by PolynomialDivision** [comment]
Merged.

**Pull request closed without merging**
