### PR TITLE
datastorage: fix nullpointer

### PR DESCRIPTION
**Pull request by PolynomialDivision**
@gongsearch and  @jonozzz could u test this?

On which architecture are u running dawn?

### CODE REVIEW

**Comment by jonozzz** [comment]
I tried this on a:
```
# cat /proc/cpuinfo
system type             : Qualcomm Atheros QCA9558 ver 1 rev 0
machine                 : Netgear EX6400
processor               : 0
cpu model               : MIPS 74Kc V5.0
```

**Comment by PolynomialDivision** [comment]
And? Still a null pointer?

Could u enable stdout in /etc/config/dawn

and grep for

    logread grep "Chosen AP"

and give me the result?

**Comment by jonozzz** [comment]
I haven't tried the null pointer fix. I'll do that later.

These are generated every 10 seconds:
```
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: -------- KICKING CLIENTS!!!---------
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: EVAL CE:40:D0:56:A1:42
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Expected throughput 0.000000 Mbit/sec
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Failed to update rssi!
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Chosen AP
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: AP is best. Client will stay:
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: bssid_addr: CE:40:D0:56:A1:42, client_addr: D4:4D:A4:E0:DD:74, freq: 5745, ht_supported: 1, vht_supported: 1, ht: 1, vht: 1, kick: 0
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: ---------------------------
...
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: -------- KICKING CLIENTS!!!---------
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: EVAL CC:40:D0:56:A1:41
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Expected throughput 31.968000 Mbit/sec
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Failed to update rssi!
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Chosen AP
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Comparing kick count! kickcount: 5 to min_kick_count: 3!
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Better AP available. Kicking client:
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: bssid_addr: CC:40:D0:56:A1:41, client_addr: 9C:8E:CD:06:42:09, freq: 2432, ht_supported: 1, vht_supported: 0, ht: 1, vht: 0, kick: 5
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Check if client is active receiving!
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: Client is probably in active transmisison. Don't kick! RxRate is: 65.000000
Fri Jun 12 13:24:40 2020 daemon.info dawn[10064]: ---------------------------
```

**Comment by PolynomialDivision** [comment]
Hmmm. The kicking function runs without any problems. o.O Okay, I don't believe that the fix will help. Please report the logread output if dawn crashes again.

**Pull request closed without merging**
