### PR TITLE
tcpsocket: implement client_read_cb with ustream_read

### PR DESCRIPTION
**Pull request by babarosaM33**
my wheels are much worse than offical wheels.

/*
 * ustream_read: read and consume data in read buffer into caller-specified
 * area.  Return length of data read.
 */
int ustream_read(struct ustream *s, char *buf, int buflen);

### CODE REVIEW

**Comment by babarosaM33** [comment]
@PolynomialDivision

**Comment by PolynomialDivision** [comment]
Did u find an example how other people are doing that? Did u tested that? ;) I want to look over this ustream stuff again.

**Comment by babarosaM33** [comment]
No example found. 

I could not test code right now,  since i am on travel.

**Comment by PolynomialDivision** [comment]
Your PR does not work for me. :/
It seems like the message is always 4 bytes to small?

**Pull request closed without merging**
