### PR TITLE
datastorage/test: improve scalability and performance

### PR DESCRIPTION
**Pull request by PolynomialDivision**
datastorage: convert to linked lists and optimise use of pointers
datastorage: AP, client, probe, auth entry and MAC list converted to
             linked list
datastorage: functions adjusted to take pointers as parameters
datastorage: optimised sort and search functions added
mac_utils: struct dawn_mac added and comparisons adjusted
general: adjust code to  call new datastorage functions
test_storage: large scale 100 AP, 3000 client, 70k probe added

[fix commit]

### CODE REVIEW

**Comment by XiaoliChan** [comment]
I use this bunch, when my client was connected my wifi minutes ago, my client say can not 'connect to internet' and solve by reconnect wifi.

The log is flood with "Connected" and "Disconnect" hostapd message.

```
Tue Aug  4 11:25:37 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 11:25:37 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 11:25:37 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 11:25:37 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 11:25:37 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 11:33:54 2020 daemon.info hostapd: wlan1: STA 02:9e:2f:c3:bd:c5 IEEE 802.11: authenticated
Tue Aug  4 11:33:54 2020 daemon.info hostapd: wlan1: STA 02:9e:2f:c3:bd:c5 IEEE 802.11: associated (aid 2)
Tue Aug  4 11:33:54 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED 02:9e:2f:c3:bd:c5
Tue Aug  4 11:33:54 2020 daemon.info hostapd: wlan1: STA 02:9e:2f:c3:bd:c5 RADIUS: starting accounting session F08D72353E75E307
Tue Aug  4 11:33:54 2020 daemon.info hostapd: wlan1: STA 02:9e:2f:c3:bd:c5 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 11:57:27 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 11:57:27 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 11:57:27 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 11:57:27 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 11:57:27 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 11:57:27 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 11:58:27 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 11:58:27 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 11:58:27 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 11:58:27 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 11:58:27 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 11:58:27 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 11:59:28 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 11:59:28 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 11:59:28 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 11:59:28 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 11:59:28 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 11:59:28 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 12:00:28 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:00:28 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 12:00:28 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 12:00:28 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:00:28 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 12:00:28 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 12:01:29 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED 02:9e:2f:c3:bd:c5
Tue Aug  4 12:01:29 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:01:29 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 12:01:29 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 12:01:29 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:01:29 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 12:01:29 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 12:01:34 2020 daemon.info hostapd: wlan1: STA 02:9e:2f:c3:bd:c5 IEEE 802.11: deauthenticated due to local deauth request
Tue Aug  4 12:02:19 2020 daemon.err uhttpd[1681]: luci: accepted login on / for root from 192.168.1.175
Tue Aug  4 12:02:29 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:02:29 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 12:02:29 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 12:02:29 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:02:29 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 12:02:29 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 12:03:30 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:03:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 12:03:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 12:03:30 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:03:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 12:03:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 12:04:30 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:04:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 12:04:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 12:04:30 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:04:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 12:04:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
Tue Aug  4 12:05:30 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:05:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: authenticated
Tue Aug  4 12:05:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 IEEE 802.11: associated (aid 1)
Tue Aug  4 12:05:30 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED ee:5c:0a:dc:67:11
Tue Aug  4 12:05:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 RADIUS: starting accounting session 6A74322A2AFA71D7
Tue Aug  4 12:05:30 2020 daemon.info hostapd: wlan1: STA ee:5c:0a:dc:67:11 WPA: pairwise key handshake completed (RSN)
```

**Comment by PolynomialDivision** [comment]
@XiaoliChan thanks for testing. I did not test the PR by myself. @Ian-Clowes made some changes and I just made a PR so I could test. Further, the PR is now patched and hopefully will fix your issues. I will test it now, too. :)

**Comment by XiaoliChan** [comment]
> @XiaoliChan thanks for testing. I did not test the PR by myself. @Ian-Clowes made some changes and I just made a PR so I could test. Further, the PR is now patched and hopefully will fix your issues. I will test it now, too. :)

okay, i will test it when PR is pass :)

**Comment by Ian-Clowes** [comment]
Hmmm.  I certainly didn't see that behaviour.  It's happening every minute by the looks of things.  Which of the "config times" items in /etc/dawn/config are set to 60?

**Comment by XiaoliChan** [comment]
Here is my `config times` parameters @Ian-Clowes .

```
config times
        option update_client '10'
        option denied_req_threshold '30'
        option remove_client '15'
        option remove_probe '30'
        option remove_ap '460'
        option update_hostapd '10'
        option update_tcp_con '10'
        option update_chan_util '5'
        option update_beacon_reports '20'
```

**Comment by PolynomialDivision** [comment]
@XiaoliChan should work now.

You can see a memory audit if u send a SIGHUP signal to dawn.

Thanks a lot @Ian-Clowes

**Comment by XiaoliChan** [comment]
@Ian-Clowes Thanks for your PR, i will test it later.

**Comment by XiaoliChan** [comment]
I think this PR is better than beforce.

But one thing i should notice that is i need to reconnect my ap after i change the dawn permanent, if i do not do that, my client can not go to internet. (In master bunch, ido not need to do that.)

<a href="https://sm.ms/image/5FArUCEZpnQ2MVi" target="_blank"></a>

**Comment by Ian-Clowes** [comment]
I've also seen that when DAWN starts it causes attached devices to be detached.  If I read the code correctly it's because the kicking algorithm can't find some information that it needs to make an informed decision (because it hasn't been running long enough to collect it), so tells the client to detach and reconnect as a way of getting the data.  The client does reattach shortly afterwards, so for example some but not all my SSH sessions to the router may survive the detach / reattach.

I was looking last night at how to add something like a grace period of 30 seconds, perhaps track when the relevant data has had a reasonable chance to arrive, or adjust the kicking algorithm to be less aggresive if there is no known better place to send a device.

I haven't reached any conclusions yet, but it's pretty much top of my mind to address.

**Comment by Ian-Clowes** [comment]
Ah, just saw your comment about master branch.  I didn't realise this behaviour had changed along the way.  I'll try and work out what could have caused it.  While making changes to the storage code I've tried to keep all original behaviours.

**Comment by PolynomialDivision** [comment]
> Ah, just saw your comment about master branch. I didn't realise this behaviour had changed along the way. I'll try and work out what could have caused it. While making changes to the storage code I've tried to keep all original behaviours.

That is happening here: https://github.com/berlin-open-wireless-lab/DAWN/blob/master/src/storage/datastorage.c#L413-L420
We could just craft a probe response frame with the information we can gather from iwinfo. Like I did with beacon reports.

**Comment by Ian-Clowes** [comment]
I thought about that.  I've made some adjustments to the kicking parts that might have a reasonable effect.  All they do is only kicj, disassociate, etc if there is a known better AP to go to.  Lack of info about the current AP is then not a reason to kick because the algorithm says we have to know about our own status to compare to others.  No info on own stae means no kick.  I think it's a safer policy overall.  In code terms better_ap_available never returns -1, just 0 or 1.  So quite a simple change,

Also changed score eval to not return -2.  It was never tested as a "magic number" and was just a placeholder for any score < 0.  A score of 0 is broadly equivalent and any value is only meaning ful if there are other positve score found.

**Comment by PolynomialDivision** [comment]
> A score of 0 is broadly equivalent and any value is only meaning ful if there are other positve score found.

I have built in a metric where values are added up. It can happen that an access point does not get a single positive value, so it has a score of 0. Nevertheless it must be preferred to an AP that has a really bad RSSI or channel utilization. Right now I use negative values for that. We can also turn this around to "is not below the worst acceptable RSSI" so every AP with acceptable RSSI will get a score of > 0 and the -2 will then get 0.

**Comment by PolynomialDivision** [comment]
>  Lack of info about the current AP is then not a reason to kick because the algorithm says we have to know about our own status to compare to others. No info on own stae means no kick.

Yeah, but maybe u will then never kick. :S A probe exchange will never happen with a connected client.
I prefer creating some dummy probe entry... This will solve the luci-app signal strength having no value.
But I'm not sure.

**Comment by PolynomialDivision** [comment]
There is a huge problem with clients doing mac randomization while scanning... >.>

**Comment by PolynomialDivision** [comment]
I made an issue for it https://github.com/berlin-open-wireless-lab/DAWN/issues/113

**Comment by XiaoliChan** [comment]
By the way, i have no idea why i can not see any [KICKING CLIENTS] log although i enable [Activate Kicking].

**Comment by PolynomialDivision** [comment]
> By the way, i have no idea why i can not see any [KICKING CLIENTS] log although i enable [Activate Kicking].

You have to enable stdout in the init script. :)

**Comment by XiaoliChan** [comment]
> > By the way, i have no idea why i can not see any [KICKING CLIENTS] log although i enable [Activate Kicking].
> 
> You have to enable stdout in the init script. :)

So, how to do this?

**Comment by PolynomialDivision** [comment]
In the `/etc/init.d/dawn` go to the line `procd_set_param stdout 0` and change it to `procd_set_param stdout 1` :)

**Comment by XiaoliChan** [comment]
> In the file `/etc/init.d/dawn` go to the line `procd_set_param stdout 0` and change it to `procd_set_param stdout 1` :)

Thank you, i test it now.

**Comment by PolynomialDivision** [comment]
> > In the file `/etc/init.d/dawn` go to the line `procd_set_param stdout 0` and change it to `procd_set_param stdout 1` :)
> 
> Thank you, i test it now.

To dump memory u can do something like

    pgrep dawn | xargs kill -SIGHUP

**Comment by Ian-Clowes** [comment]
> 
> 
> > A score of 0 is broadly equivalent and any value is only meaning ful if there are other positve score found.
> 
> I have built in a metric where values are added up. It can happen that an access point does not get a single positive value, so it has a score of 0. Nevertheless it must be preferred to an AP that has a really bad RSSI or channel utilization. Right now I use negative values for that. We can also turn this around to "is not below the worst acceptable RSSI" so every AP with acceptable RSSI will get a score of > 0 and the -2 will then get 0.

I agree with the concept of always being able to distinguish good from bad, and kicking based on that.  I think lack of information (and hence not sure if good or bad) should not be a reason to kick something.  Several ways to address it, and all are good IMHO.

**Comment by XiaoliChan** [comment]
I have test the `Kick function`, but I check the log, it did not seem kick client always although I set `option min_number_to_kick` to `0`.(Should I disable `Use Station Count` function? because I checked what you said in this post )

And I found something interesting in the log
```
Thu Aug  6 21:38:37 2020 daemon.info dawn[5202]: -------- IW INFO UPDATE!!!---------
Thu Aug  6 21:38:37 2020 daemon.info dawn[5202]: EVAL 20:76:93:3E:3A:F0
Thu Aug  6 21:38:37 2020 daemon.info dawn[5202]: ---------------------------
Thu Aug  6 21:38:37 2020 daemon.info dawn[5202]: -------- KICKING CLIENTS!!!---------
Thu Aug  6 21:38:37 2020 daemon.info dawn[5202]: EVAL 20:76:93:3E:3A:F0 
Thu Aug  6 21:46:51 2020 daemon.info dawn[5202]: ---------------------------
```
I method the `IW INFO UPDATE` log, the `20:76:93:3E:3A:F0` just is my 2.4GHz wireless mac of current ap. By the way, I did not have any connection of this BSSID.
In my opinion, the `kick function` should eval the 2.4GHz both 5GHz.

And here is my current ap `iwinfo`
```
root@AP-Room1:/# iwinfo 
wlan0     ESSID: "Hydrogen-2.4G"
          Access Point: 20:76:93:3E:3A:F0
          Mode: Master  Channel: 1 (2.412 GHz)
          Tx-Power: 28 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: unknown
          Bit Rate: unknown
          Encryption: WPA2 PSK (CCMP)
          Type: nl80211  HW Mode(s): 802.11bgn
          Hardware: 14C3:7603 14C3:7603 [MediaTek MT7603E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0

wlan1     ESSID: "Hydrogen-5G"
          Access Point: 20:76:93:3E:3A:F2
          Mode: Master  Channel: 52 (5.260 GHz)
          Tx-Power: 21 dBm  Link Quality: 48/70
          Signal: -62 dBm  Noise: unknown
          Bit Rate: 536.2 MBit/s
          Encryption: WPA2 PSK (CCMP)
          Type: nl80211  HW Mode(s): 802.11nac
          Hardware: 14C3:7662 14C3:7662 [MediaTek MT76x2E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy1
```


Here is the client message in the log.(`20:76:93:3D:75:80` is my second ap in another room)
```
Thu Aug  6 21:54:05 2020 daemon.info dawn[5202]: --------Clients------
Thu Aug  6 21:54:05 2020 daemon.info dawn[5202]: Client Entry Last: 3
Thu Aug  6 21:54:05 2020 daemon.info dawn[5202]: bssid_addr: 20:76:93:3D:75:80, client_addr: 38:A4:ED:AB:F5:55, freq: 2432, ht_supported: 1, vht_supported: 0, ht: 1, vht: 0, kick: 0
Thu Aug  6 21:54:05 2020 daemon.info dawn[5202]: bssid_addr: 20:76:93:3E:3A:F2, client_addr: 02:9E:2F:C3:BD:C5, freq: 5260, ht_supported: 1, vht_supported: 1, ht: 1, vht: 1, kick: 0
Thu Aug  6 21:54:05 2020 daemon.info dawn[5202]: bssid_addr: 20:76:93:3E:3A:F2, client_addr: 6C:6A:77:5F:5F:73, freq: 5260, ht_supported: 1, vht_supported: 1, ht: 1, vht: 1, kick: 0
```

**Pull request merged**
